import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string | string[];
  isRTL: boolean;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.products': 'Solutions',
    'nav.features': 'Why Us',
    'nav.contact': 'Contact',
    'nav.menu': 'Menu',
    'nav.close': 'Close menu',
    'nav.open': 'Open menu',

    'hero.chip': 'AI Solutions & Services',
    'hero.title': 'Intelligent AI Solutions\nfor Modern Business',
    'hero.subtitle': 'Transform your business with cutting-edge artificial intelligence. From custom AI development to intelligent automation, we build solutions that learn, adapt, and drive growth.',
    'hero.cta': 'Start Your Project',
    'hero.cta_secondary': 'Explore Our AI',
    'hero.scroll': 'Scroll',
    'hero.pricing_monthly': '499',

    'services.section': 'Our Services',
    'services.title': 'AI Services Tailored\nfor Your Success',
    'services.subtitle': 'End-to-end AI consulting and development services designed to transform your business operations',
    'services.consulting.eyebrow': 'Strategy',
    'services.consulting.title': 'AI Consulting',
    'services.consulting.description': 'Strategic AI roadmap development, feasibility analysis, and technology selection tailored to your business goals.',
    'services.custom.eyebrow': 'Development',
    'services.custom.title': 'Custom AI Development',
    'services.custom.description': 'Build bespoke AI models, NLP systems, computer vision solutions, and predictive analytics platforms from scratch.',
    'services.integration.eyebrow': 'Integration',
    'services.integration.title': 'AI Integration',
    'services.integration.description': 'Seamlessly integrate AI capabilities into your existing systems, workflows, and business processes.',
    'services.automation.eyebrow': 'Automation',
    'services.automation.title': 'Intelligent Automation',
    'services.automation.description': 'Automate repetitive tasks, decision-making processes, and complex workflows with AI-powered automation.',

    'products.section': 'AI Solutions',
    'products.title': 'Our Best AI Solutions',
    'products.subtitle': 'Production-ready AI systems built with modern architectures to solve real business problems',
    'products.agentic.title': 'Agentic AI Systems',
    'products.agentic.description': 'Autonomous AI agents that plan, reason, and execute multi-step tasks across your business tools with minimal human oversight.',
    'products.agentic.tags': ['Tool Use', 'Multi-Agent', 'Autonomous'],
    'products.rag.title': 'RAG Systems',
    'products.rag.description': 'Retrieval-Augmented Generation that grounds LLM responses in your private documents, knowledge bases, and enterprise data.',
    'products.rag.tags': ['Vector Search', 'Context Aware', 'Enterprise Data'],
    'products.chatbot.title': 'Intelligent Chatbots',
    'products.chatbot.description': 'Context-aware conversational AI for customer support, lead qualification, and internal helpdesks with human-like responses.',
    'products.chatbot.tags': ['24/7 Support', 'Multi-language', 'Lead Gen'],
    'products.analytics.title': 'Predictive Analytics',
    'products.analytics.description': 'ML-powered forecasting, anomaly detection, and trend analysis that turn your raw data into actionable business intelligence.',
    'products.analytics.tags': ['Forecasting', 'Anomaly Detection', 'BI'],
    'products.ocr.title': 'Smart Document Processing',
    'products.ocr.description': 'AI-driven OCR and document understanding that extracts, validates, and routes information from invoices, contracts, and forms.',
    'products.ocr.tags': ['Extraction', 'Validation', 'Automation'],
    'products.vision.title': 'Computer Vision',
    'products.vision.description': 'Deep learning models for image recognition, quality inspection, object detection, and visual monitoring across industries.',
    'products.vision.tags': ['Detection', 'Inspection', 'Monitoring'],

    'products.learn_more': 'Learn More',
    'products.know_more': 'Know more',
    'products.built_with': 'Built with',
    'products.view_all': 'View all solutions',
    'products.tagline': 'beyond intelligence',

    'product.back_home': 'Back to Home',
    'product.features': 'Key Features',
    'product.use_cases': 'Use Cases',
    'product.benefits': 'Benefits',
    'product.cta_title_prefix': 'Interested in ',
    'product.cta_title_suffix': '?',
    'product.cta_subtitle': 'Contact us to learn how we can tailor this solution to your business needs.',
    'product.cta_button': 'Contact Us',

    'features.section': 'Why MovinWare AI',
    'features.title': 'Built Different.\nBuilt Better.',
    'features.subtitle': 'What sets our AI solutions apart from the competition',
    'features.expertise.title': 'Domain Expertise',
    'features.expertise.description': 'Deep knowledge across education, healthcare, retail, manufacturing, and logistics sectors.',
    'features.localization.title': 'MENA Localization',
    'features.localization.description': 'Full Arabic language support, RTL interfaces, and cultural adaptation for the MENA market.',
    'features.support.title': 'Ongoing Support',
    'features.support.description': 'Dedicated support team with 24/7 monitoring, regular updates, and continuous optimization.',
    'features.security.title': 'Enterprise Security',
    'features.security.description': 'SOC2-compliant infrastructure with end-to-end encryption and data protection standards.',

    'contact.section': 'Contact Us',
    'contact.title': 'Start Your AI Journey',
    'contact.subtitle': 'Connect with our AI experts to discuss your project requirements',
    'contact.cta.title': 'Ready to Start?',
    'contact.cta.description': 'Send us a message directly — we\'ll reply within 24 hours.',
    'contact.cta.button': 'Email Us',
    'contact.cta.note': 'Or reach out via phone or mail below.',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service Interest',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.sent': 'Message Sent!',
    'contact.form.message_placeholder': 'Tell us about your AI project...',
    'contact.form.error.name': 'Please enter your name',
    'contact.form.error.email': 'Please enter your email',
    'contact.form.error.email_invalid': 'Please enter a valid email',
    'contact.form.error.message': 'Please enter your message',
    'contact.form.toast_success': 'Message sent successfully!',
    'contact.form.toast_success_desc': 'We\'ll respond within 24 hours.',
    'contact.form.toast_error': 'Failed to send message',
    'contact.form.toast_error_desc': 'Please try again or email us at info@movinware.com',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.info.location_value': 'Online',
    'contact.inquiry.general': 'General Inquiry',
    'contact.inquiry.consulting': 'AI Consulting',
    'contact.inquiry.custom': 'Custom Development',
    'contact.inquiry.integration': 'AI Integration',
    'contact.inquiry.support': 'Support',
    'contact.inquiry.demo': 'Demo Request',

    'footer.description': 'AI-powered solutions designed to transform modern businesses.\nFrom intelligent automation to custom AI development, we build the future of your business.',
    'footer.quick_links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2026 MovinWare AI. All rights reserved.',
    'footer.built_by': 'Developed by MovinWare Team',

    'cta.title': 'Ready to Transform\nYour Business with AI?',
    'cta.subtitle': 'Let our AI experts help you build intelligent solutions that drive growth and efficiency.',
    'cta.button': 'Get Started Today',

    'pricing.kicker': 'Simple, transparent pricing',
    'pricing.title': 'Pricing that fits on a\nsticky note.',
    'pricing.see_full': 'See full pricing',
    'pricing.trial_note': 'Every plan starts with a 14-day free trial — no charge until it ends. Compare plans in detail →',
    'pricing.tiers.starter.name': 'Starter',
    'pricing.tiers.starter.eyebrow': 'For small teams',
    'pricing.tiers.starter.price': '$499',
    'pricing.tiers.starter.period': '/month',
    'pricing.tiers.starter.blurb': 'Perfect for getting started with AI.',
    'pricing.tiers.starter.detail': 'Up to 10,000 AI responses/month included',
    'pricing.tiers.starter.cta': 'Start free trial',
    'pricing.tiers.growth.name': 'Growth',
    'pricing.tiers.growth.eyebrow': 'For growing teams',
    'pricing.tiers.growth.price': '$1,499',
    'pricing.tiers.growth.period': '/month',
    'pricing.tiers.growth.blurb': 'For teams scaling AI across the org.',
    'pricing.tiers.growth.detail': 'Up to 50,000 AI responses/month included',
    'pricing.tiers.growth.cta': 'Start free trial',
    'pricing.tiers.scale.name': 'Scale',
    'pricing.tiers.scale.eyebrow': 'For enterprise',
    'pricing.tiers.scale.price': 'Custom',
    'pricing.tiers.scale.period': '/month',
    'pricing.tiers.scale.blurb': 'High volume, fully white-labeled.',
    'pricing.tiers.scale.detail': 'Unlimited responses, dedicated support',
    'pricing.tiers.scale.cta': 'Contact sales',

    'faq.kicker': 'FAQ',
    'faq.q1': 'What is MovinWare AI?',
    'faq.a1': 'MovinWare AI provides custom AI solutions and services — from strategic consulting to full-stack development of agentic systems, RAG pipelines, and intelligent automation. We help businesses in MENA and globally adopt AI that works.',
    'faq.q2': 'How do I get started?',
    'faq.a2': 'Reach out via the contact form or email us at info@movinware.com. We\'ll schedule a discovery call to understand your needs and propose a tailored approach.',
    'faq.q3': 'Which industries do you serve?',
    'faq.a3': 'We have deep expertise in education, healthcare, retail, manufacturing, logistics, and financial services — but our AI frameworks adapt to any domain.',
    'faq.q4': 'Do you support Arabic and RTL?',
    'faq.a4': 'Yes. Full Arabic language support, RTL interfaces, and cultural adaptation for the MENA market are built into every solution we deliver.',
    'faq.q5': 'What is your pricing model?',
    'faq.a5': 'We offer flat monthly plans with no per-seat fees — Starter at $499/mo, Growth at $1,499/mo, and custom Scale plans. Every plan includes a 14-day free trial.',

    'marquee.consulting': 'AI Consulting',
    'marquee.custom': 'Custom Development',
    'marquee.automation': 'Automation',
    'marquee.ml': 'Machine Learning',
    'marquee.genai': 'Generative AI',
    'marquee.chatbots': 'Chatbots',
    'marquee.vision': 'Computer Vision',
    'marquee.nlp': 'NLP',
    'marquee.rag': 'RAG',
    'marquee.agents': 'AI Agents',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.products': 'الحلول',
    'nav.features': 'لماذا نحن',
    'nav.contact': 'تواصل معنا',
    'nav.menu': 'القائمة',
    'nav.close': 'إغلاق القائمة',
    'nav.open': 'فتح القائمة',

    'hero.chip': 'حلول وخدمات الذكاء الاصطناعي',
    'hero.title': 'حلول ذكاء اصطناعي\nللأعمال الحديثة',
    'hero.subtitle': ' حوّل أعمالك بأحدث تقنيات الذكاء الاصطناعي. من تطوير حلول الذكاء الاصطناعي المخصصة إلى الأتمتة الذكية، نبني حلولًا تتعلم وتتكيف وتدفع النمو.',
    'hero.cta': 'ابدأ مشروعك',
    'hero.cta_secondary': 'استكشف حلولنا',
    'hero.scroll': 'مرر',
    'hero.pricing_monthly': '1,870',

    'services.section': 'خدماتنا',
    'services.title': 'خدمات ذكاء اصطناعي\nمصممة لنجاحك',
    'services.subtitle': 'خدمات استشارية وتطوير شاملة للذكاء الاصطناعي مصممة لتحويل عمليات أعمالك',
    'services.consulting.eyebrow': 'استراتيجية',
    'services.consulting.title': 'استشارات الذكاء الاصطناعي',
    'services.consulting.description': 'تطوير خارطة طريق الذكاء الاصطناعي الاستراتيجية وتحليل الجدوى واختيار التقنيات المخصص لأهداف عملك.',
    'services.custom.eyebrow': 'تطوير',
    'services.custom.title': 'تطوير ذكاء اصطناعي مخصص',
    'services.custom.description': 'بناء نماذج ذكاء اصطناعي مخصصة وأنظمة معالجة اللغات الطبيعية وحلول الرؤية الحاسوبية من الصفر.',
    'services.integration.eyebrow': 'تكامل',
    'services.integration.title': 'تكامل الذكاء الاصطناعي',
    'services.integration.description': 'دمج قدرات الذكاء الاصطناعي بسلاسة في أنظمتك وعمليات عملك الحالية.',
    'services.automation.eyebrow': 'أتمتة',
    'services.automation.title': 'أتمتة ذكية',
    'services.automation.description': 'أتمتة المهام المتكررة وعمليات اتخاذ القرارات وسير العمل المعقدة بأتمتة مدعومة بالذكاء الاصطناعي.',

    'products.section': 'حلولنا',
    'products.title': 'أفضل حلول الذكاء الاصطناعي',
    'products.subtitle': 'أنظمة ذكاء اصطناعي جاهزة للإنتاج مبنية ببنية حديثة لحل مشاكل الأعمال الحقيقية',
    'products.agentic.title': 'أنظمة الوكيل الذكي',
    'products.agentic.description': 'وكلاء ذكاء اصطناعي مستقلون يخططون ويبررون وينفذون مهام متعددة الخطوات عبر أدوات أعمالك ب最少 إشراف بشري.',
    'products.agentic.tags': ['استخدام الأدوات', 'وكيل متعدد', 'مستقل'],
    'products.rag.title': 'أنظمة RAG',
    'products.rag.description': 'توليد معزز بالاسترجاع يضمن ردود نماذج اللغة الكبيرة في مستنداتك الخاصة وقواعد معرفتك وبيانات مؤسستك.',
    'products.rag.tags': ['بحث المتجهات', 'وعي بالسياق', 'بيانات المؤسسات'],
    'products.chatbot.title': 'روبوتات محادثة ذكية',
    'products.chatbot.description': 'ذكاء اصطناعي محادث واعٍ بالسياق لدعم العملاء وتأهيل العملاء المحتملين وأطر المساعدة الداخلية.',
    'products.chatbot.tags': ['دعم 24/7', 'متعدد اللغات', 'توليد عملاء'],
    'products.analytics.title': 'التحليلات التنبؤية',
    'products.analytics.description': 'تنبؤات مدعومة بالتعلم الآلي واكتشاف الشذوذ وتحليل الاتجاهات التي تحول بياناتك الخام إلى ذكاء أعمال قابل للتنفيذ.',
    'products.analytics.tags': ['تنبؤ', 'اكتشاف الشذوذ', 'ذكاء أعمال'],
    'products.ocr.title': 'معالجة المستندات الذكية',
    'products.ocr.description': 'تعرّف ضوئي على الحروف مدعوم بالذكاء الاصطناعي وفهم المستندات يستخرج ويتحقق ويوجه المعلومات من الفواتير والعقود والنماذج.',
    'products.ocr.tags': ['استخراج', 'تحقق', 'أتمتة'],
    'products.vision.title': 'الرؤية الحاسوبية',
    'products.vision.description': 'نماذج تعلم عميق للتعرف على الصور وفحص الجودة واكتشاف الكائنات والمراقبة البصرية عبر الصناعات.',
    'products.vision.tags': ['اكتشاف', 'فحص', 'مراقبة'],

    'products.learn_more': 'اعرف المزيد',
    'products.know_more': 'اعرف المزيد',
    'products.built_with': 'مبنية بـ',
    'products.view_all': 'عرض جميع الحلول',
    'products.tagline': 'ما وراء الذكاء',

    'product.back_home': 'العودة للرئيسية',
    'product.features': 'الميزات الرئيسية',
    'product.use_cases': 'حالات الاستخدام',
    'product.benefits': 'الفوائد',
    'product.cta_title_prefix': 'مهتم بـ ',
    'product.cta_title_suffix': '؟',
    'product.cta_subtitle': 'تواصل معنا لمعرفة كيف يمكننا تخصيص هذه الحلول لاحتياجات أعمالك.',
    'product.cta_button': 'تواصل معنا',

    'features.section': 'لماذا MovinWare AI',
    'features.title': 'مختلف.\nأفضل.',
    'features.subtitle': 'ما يميز حلول الذكاء الاصطناعي لدينا عن المنافسين',
    'features.expertise.title': 'خبرة في المجال',
    'features.expertise.description': 'معرفة عميقة عبر قطاعات التعليم والصحة والتجارة والتصنيع واللوجستيات.',
    'features.localization.title': 'توطين MENA',
    'features.localization.description': 'دعم كامل للغة العربية وواجهات من اليمين لليسار والتكيف الثقافي لسوق MENA.',
    'features.support.title': 'دعم مستمر',
    'features.support.description': 'فريق دعم مخصص مع مراقبة على مدار الساعة وتحديثات منتظمة وتحسين مستمر.',
    'features.security.title': 'أمان المؤسسات',
    'features.security.description': 'بنية تحتية متوافقة مع SOC2 مع تشفير شامل ومعايير حماية البيانات.',

    'contact.section': 'تواصل معنا',
    'contact.title': 'ابدأ رحلة الذكاء الاصطناعي',
    'contact.subtitle': 'تواصل مع خبراء الذكاء الاصطناعي لدينا لمناقشة متطلبات مشروعك',
    'contact.cta.title': 'مستعد للبدء؟',
    'contact.cta.description': 'أرسل لنا رسالة مباشرة — سنرد خلال 24 ساعة.',
    'contact.cta.button': 'راسلنا',
    'contact.cta.note': 'أو تواصل عبر الهاتف أو البريد أدناه.',
    'contact.form.title': 'أرسل رسالة',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.company': 'الشركة',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.service': 'الخدمة المطلوبة',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.sending': 'جاري الإ送信...',
    'contact.form.sent': 'تم الإرسال!',
    'contact.form.message_placeholder': 'أخبرنا عن مشروع الذكاء الاصطناعي الخاص بك...',
    'contact.form.error.name': 'يرجى إدخال اسمك',
    'contact.form.error.email': 'يرجى إدخال بريدك الإلكتروني',
    'contact.form.error.email_invalid': 'يرجى إدخال بريد إلكتروني صالح',
    'contact.form.error.message': 'يرجى إدخال رسالتك',
    'contact.form.toast_success': 'تم إرسال الرسالة بنجاح!',
    'contact.form.toast_success_desc': 'سنرد خلال 24 ساعة.',
    'contact.form.toast_error': 'فشل إرسال الرسالة',
    'contact.form.toast_error_desc': 'يرجى المحاولة مرة أخرى أو مراسلتنا على info@movinware.com',
    'contact.info.title': 'معلومات التواصل',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.phone': 'الهاتف',
    'contact.info.location': 'الموقع',
    'contact.info.location_value': 'عبر الإنترنت',
    'contact.inquiry.general': 'استفسار عام',
    'contact.inquiry.consulting': 'استشارات الذكاء الاصطناعي',
    'contact.inquiry.custom': 'تطوير مخصص',
    'contact.inquiry.integration': 'تكامل الذكاء الاصطناعي',
    'contact.inquiry.support': 'الدعم',
    'contact.inquiry.demo': 'طلب عرض',

    'footer.description': 'حلول مدعومة بالذكاء الاصطناعي مصممة لتحويل الأعمال الحديثة.\nمن الأتمتة الذكية إلى تطوير الذكاء الاصطناعي المخصص، نبني مستقبل أعمالك.',
    'footer.quick_links': 'روابط سريعة',
    'footer.contact': 'التواصل',
    'footer.copyright': '© 2026 MovinWare AI. جميع الحقوق محفوظة.',
    'footer.built_by': 'تطوير فريق MovinWare',

    'cta.title': 'مستعد لتحويل\nأعمالك بالذكاء الاصطناعي؟',
    'cta.subtitle': 'دع خبراء الذكاء الاصطناعي لدينا يساعدونك في بناء حلول ذكية تدفع النمو والكفاءة.',
    'cta.button': 'ابدأ اليوم',

    'pricing.kicker': 'تسعير بسيط وشفاف',
    'pricing.title': 'تسعير يناسب\nورقة لاصقة.',
    'pricing.see_full': 'عرض التسعير الكامل',
    'pricing.trial_note': 'كل خطة تبدأ بتجربة مجانية لمدة 14 يومًا — لا يتم تحصيل رسوم حتى تنتهي. مقارنة تفصيلية للخطط →',
    'pricing.tiers.starter.name': 'البداية',
    'pricing.tiers.starter.eyebrow': 'للفرق الصغيرة',
    'pricing.tiers.starter.price': '1,870 ر.س',
    'pricing.tiers.starter.period': '/شهر',
    'pricing.tiers.starter.blurb': 'مثالي للبدء مع الذكاء الاصطناعي.',
    'pricing.tiers.starter.detail': 'حتى 10,000 رد ذكاء اصطناعي/شهر مشمول',
    'pricing.tiers.starter.cta': 'بدء التجربة المجانية',
    'pricing.tiers.growth.name': 'النمو',
    'pricing.tiers.growth.eyebrow': 'للفرق النامية',
    'pricing.tiers.growth.price': '5,600 ر.س',
    'pricing.tiers.growth.period': '/شهر',
    'pricing.tiers.growth.blurb': 'للفرق التي توسع الذكاء الاصطناعي في المؤسسة.',
    'pricing.tiers.growth.detail': 'حتى 50,000 رد ذكاء اصطناعي/شهر مشمول',
    'pricing.tiers.growth.cta': 'بدء التجربة المجانية',
    'pricing.tiers.scale.name': 'التوسع',
    'pricing.tiers.scale.eyebrow': 'للمؤسسات',
    'pricing.tiers.scale.price': 'مخصص',
    'pricing.tiers.scale.period': '/شهر',
    'pricing.tiers.scale.blurb': 'حجم عالٍ، علامات تجارية بيضاء بالكامل.',
    'pricing.tiers.scale.detail': 'ردود غير محدودة، دعم مخصص',
    'pricing.tiers.scale.cta': 'تواصل مع المبيعات',

    'faq.kicker': 'الأسئلة الشائعة',
    'faq.q1': 'ما هو MovinWare AI؟',
    'faq.a1': 'تقدم MovinWare AI حلول وخدمات ذكاء اصطناعي مخصصة — من الاستشارات الاستراتيجية إلى التطوير الكامل لأنظمة الوكلاء، خطوط أنابيب RAG، والأتمتة الذكية. نساعد الشركات في MENA والعالم على تبني الذكاء الاصطناعي الذي يعمل.',
    'faq.q2': 'كيف أبدأ؟',
    'faq.a2': 'تواصل عبر نموذج الاتصال أو راسلنا على info@movinware.com. سنحدد مكالمة استكشافية لفهم احتياجاتك واقتراح نهج مخصص.',
    'faq.q3': 'ما هي الصناعات التي تخدمونها؟',
    'faq.a3': 'لدينا خبرة عميقة في التعليم، الرعاية الصحية، التجزئة، التصنيع، اللوجستيات، والخدمات المالية — لكن أطر الذكاء الاصطناعي لدينا تتكيف مع أي مجال.',
    'faq.q4': 'هل تدعمون العربية و RTL؟',
    'faq.a4': 'نعم. دعم كامل للغة العربية، واجهات RTL، والتكيف الثقافي لسوق MENA مدمج في كل حل نقدمه.',
    'faq.q5': 'ما هو نموذج التسعير الخاص بكم؟',
    'faq.a5': 'نقدم خطط شهرية ثابتة بدون رسوم لكل مقعد — البداية 1,870 ر.س/شهر، النمو 5,600 ر.س/شهر، وخطط توسع مخصصة. كل خطة تتضمن تجربة مجانية لمدة 14 يومًا.',

    'marquee.consulting': 'استشارات الذكاء الاصطناعي',
    'marquee.custom': 'تطوير مخصص',
    'marquee.automation': 'الأتمتة',
    'marquee.ml': 'تعلم الآلة',
    'marquee.genai': 'الذكاء الاصطناعي التوليدي',
    'marquee.chatbots': 'روبوتات المحادثة',
    'marquee.vision': 'الرؤية الحاسوبية',
    'marquee.nlp': 'معالجة اللغة الطبيعية',
    'marquee.rag': 'RAG',
    'marquee.agents': 'وكلاء الذكاء الاصطناعي',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<string>(() => {
    return localStorage.getItem("mw-lang") === "ar" ? "ar" : "en";
  });

  const setLanguage = (lang: string) => {
    localStorage.setItem("mw-lang", lang);
    setLanguageState(lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string | string[] => {
    const result = translations[language as keyof typeof translations]?.[key as keyof typeof translations.en];
    if (result === undefined) return key;
    return result;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};